services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: fittech_dev
      POSTGRES_USER: fittech
      POSTGRES_PASSWORD: fittech
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fittech -d fittech_dev"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10

  django:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app          # hot reload
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery -A brahim worker -l info -Q default,notifications,payments,analytics,scheduled
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery -A brahim beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  flower:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery -A brahim flower --port=5555
    ports:
      - "5555:5555"
    env_file: .env
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django

volumes:
  pg_data:
