# Generated by Django 5.0.4 on 2026-03-04 00:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_enable_rls"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("method", models.CharField(max_length=10)),
                ("path", models.TextField()),
                ("status_code", models.PositiveSmallIntegerField()),
                ("duration_ms", models.PositiveIntegerField()),
                ("gym_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("user_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("is_slow", models.BooleanField(db_index=True, default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "request_logs",
                "indexes": [
                    models.Index(fields=["status_code", "timestamp"], name="request_log_status_timestamp_idx"),
                    models.Index(fields=["path", "timestamp"], name="request_log_path_timestamp_idx"),
                ],
            },
        ),
    ]
