# Generated by Django 5.0.4 on 2026-03-06 00:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_request_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event", models.CharField(db_index=True, max_length=64)),
                (
                    "level",
                    models.CharField(
                        choices=[("INFO", "Info"), ("ERROR", "Error")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "system_logs",
            },
        ),
    ]
