# Generated by Django 5.0.4 on 2026-03-06 00:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_systemlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="DBSchemaVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("git_sha", models.CharField(db_index=True, max_length=64)),
                ("version_label", models.CharField(blank=True, db_index=True, max_length=128)),
                ("environment", models.CharField(db_index=True, max_length=32)),
                ("migration_heads", models.JSONField(default=dict)),
                ("notes", models.JSONField(blank=True, default=dict)),
                ("applied_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "db_schema_versions",
                "indexes": [
                    models.Index(fields=["environment", "applied_at"], name="db_schema_env_applied_idx"),
                ],
            },
        ),
    ]
