# Generated by Django 5.0.4 on 2026-03-06 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_dbschemaversion"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="requestlog",
            new_name="reqlog_status_ts_idx",
            old_name="request_log_status_timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="requestlog",
            new_name="reqlog_path_ts_idx",
            old_name="request_log_path_timestamp_idx",
        ),
    ]
