# Generated by Django 5.0.4 on 2026-03-11 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_request_log_indexes'),
        ('notifications', '0003_alter_notification_gym_and_more'),
        ('users', '0007_alter_coachapplication_gym_alter_coachprofile_gym_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='errorlog',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='errorlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='platformownership',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='platformownership',
            name='user',
        ),
        migrations.DeleteModel(
            name='AccessLog',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='ErrorLog',
        ),
        migrations.DeleteModel(
            name='Gym',
        ),
        migrations.DeleteModel(
            name='PlatformOwnership',
        ),
    ]
