# Generated by Django 5.0.4 on 2026-03-09 10:00

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def populate_retention_fields(apps, schema_editor):
    AuditLog = apps.get_model("core", "AuditLog")
    AccessLog = apps.get_model("core", "AccessLog")
    ErrorLog = apps.get_model("core", "ErrorLog")
    SystemLog = apps.get_model("core", "SystemLog")

    for audit_log in AuditLog.objects.all().iterator():
        updates = []
        if audit_log.user_id is None and audit_log.actor_id is not None:
            audit_log.user_id = audit_log.actor_id
            updates.append("user")
        if audit_log.timestamp is None:
            audit_log.timestamp = audit_log.created_at
            updates.append("timestamp")
        if audit_log.data is None:
            audit_log.data = {
                "target_id": str(audit_log.target_id) if audit_log.target_id else None,
                "target_table": audit_log.target_table,
                "old_values": audit_log.old_values,
                "new_values": audit_log.new_values,
                "ip_address": audit_log.ip_address,
                "user_agent": audit_log.user_agent,
            }
            updates.append("data")
        if updates:
            audit_log.save(update_fields=updates)

    for access_log in AccessLog.objects.all().iterator():
        if access_log.timestamp is None:
            access_log.timestamp = access_log.accessed_at
            access_log.save(update_fields=["timestamp"])

    for error_log in ErrorLog.objects.all().iterator():
        updates = []
        if error_log.timestamp is None:
            error_log.timestamp = error_log.created_at
            updates.append("timestamp")
        if not error_log.traceback and error_log.stack_trace:
            error_log.traceback = error_log.stack_trace
            updates.append("traceback")
        if updates:
            error_log.save(update_fields=updates)

    for system_log in SystemLog.objects.all().iterator():
        updates = []
        if system_log.performed_at is None:
            system_log.performed_at = system_log.created_at
            updates.append("performed_at")
        if not system_log.operation and system_log.event:
            system_log.operation = system_log.event
            updates.append("operation")
        if not system_log.detail and system_log.message:
            system_log.detail = system_log.message
            updates.append("detail")
        if updates:
            system_log.save(update_fields=updates)


def rollback_retention_fields(apps, schema_editor):
    AuditLog = apps.get_model("core", "AuditLog")
    ErrorLog = apps.get_model("core", "ErrorLog")
    SystemLog = apps.get_model("core", "SystemLog")

    for audit_log in AuditLog.objects.exclude(data__isnull=True).iterator():
        updates = []
        payload = audit_log.data or {}

        if audit_log.actor_id is None and audit_log.user_id is not None:
            audit_log.actor_id = audit_log.user_id
            updates.append("actor")

        target_id = payload.get("target_id")
        if audit_log.target_id is None and target_id:
            try:
                audit_log.target_id = uuid.UUID(str(target_id))
            except (TypeError, ValueError):
                pass
            else:
                updates.append("target_id")

        if not audit_log.target_table and payload.get("target_table"):
            audit_log.target_table = payload["target_table"]
            updates.append("target_table")
        if audit_log.old_values is None and payload.get("old_values") is not None:
            audit_log.old_values = payload["old_values"]
            updates.append("old_values")
        if audit_log.new_values is None and payload.get("new_values") is not None:
            audit_log.new_values = payload["new_values"]
            updates.append("new_values")
        if not audit_log.ip_address and payload.get("ip_address"):
            audit_log.ip_address = payload["ip_address"]
            updates.append("ip_address")
        if not audit_log.user_agent and payload.get("user_agent"):
            audit_log.user_agent = payload["user_agent"]
            updates.append("user_agent")

        if updates:
            audit_log.save(update_fields=updates)

    for error_log in ErrorLog.objects.iterator():
        if not error_log.stack_trace and error_log.traceback:
            error_log.stack_trace = error_log.traceback
            error_log.save(update_fields=["stack_trace"])

    for system_log in SystemLog.objects.iterator():
        updates = []
        if not system_log.event and system_log.operation:
            system_log.event = system_log.operation
            updates.append("event")
        if not system_log.message and system_log.detail:
            system_log.message = system_log.detail
            updates.append("message")
        if updates:
            system_log.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rename_request_log_indexes"),
        ("users", "0005_user_retention_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="timestamp",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="compliance_audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accesslog",
            name="ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accesslog",
            name="path",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="accesslog",
            name="timestamp",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="errorlog",
            name="level",
            field=models.CharField(db_index=True, default="ERROR", max_length=16),
        ),
        migrations.AddField(
            model_name="errorlog",
            name="timestamp",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="errorlog",
            name="traceback",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="systemlog",
            name="detail",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="systemlog",
            name="operation",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="systemlog",
            name="performed_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="accesslog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="access_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(
            populate_retention_fields,
            reverse_code=rollback_retention_fields,
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="accesslog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="errorlog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="systemlog",
            name="performed_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
