# Generated by Django 5.0.4 on 2026-03-03 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailotpverification_purpose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailotpverification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='emailotpverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL),
        ),
    ]
