# Generated by Django 5.0.4 on 2026-03-06 00:00

from django.db import migrations, models


def seed_session_cleanup_periodic_task(apps, schema_editor):
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="0",
        hour="3",
        day_of_week="0",
        day_of_month="*",
        month_of_year="*",
        timezone="UTC",
    )

    PeriodicTask.objects.update_or_create(
        name="users.session-log-cleanup-weekly",
        defaults={
            "task": "apps.users.tasks.cleanup_session_logs",
            "crontab": schedule,
            "enabled": True,
            "queue": "scheduled",
        },
    )


def remove_session_cleanup_periodic_task(apps, schema_editor):
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    PeriodicTask.objects.filter(
        name="users.session-log-cleanup-weekly",
        task="apps.users.tasks.cleanup_session_logs",
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_beat", "0018_improve_crontab_helptext"),
        ("users", "0003_emailotpverification_purpose"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="sessionlog",
            index=models.Index(fields=["user", "is_revoked"], name="sessionlog_user_revoked_idx"),
        ),
        migrations.RunPython(
            seed_session_cleanup_periodic_task,
            reverse_code=remove_session_cleanup_periodic_task,
        ),
    ]
