# Generated by Codex on 2026-03-07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_emailotpverification_options_and_more"),
        ("users", "0004_sessionlog_cleanup_job"),
    ]

    operations = []
