# Generated by Django 5.0.4 on 2026-03-10 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_0004_emailotp_and_sessionlog'),
        ('users', '0005_user_retention_fields'),
    ]

    operations = [
    ]
