# Generated by Django 5.0.4 on 2026-03-11 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_gym_require_2fa'),
        ('users', '0006_user_totp_enabled_user_totp_secret_totpbackupcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachapplication',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_applications', to='gyms.gym'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profiles', to='gyms.gym'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_profiles', to='gyms.gym'),
        ),
        migrations.AlterField(
            model_name='sessionlog',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_logs', to='gyms.gym'),
        ),
        migrations.AlterField(
            model_name='usergymrole',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='gyms.gym'),
        ),
        migrations.AlterField(
            model_name='warning',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='gyms.gym'),
        ),
    ]
