# Generated by Django 5.0.4 on 2026-03-09 14:06

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_user_totp_enabled_user_totp_secret_totpbackupcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=3)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('timezone', models.CharField(default='Africa/Algiers', help_text="IANA timezone name, e.g. 'Africa/Algiers', 'Europe/Paris'.", max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='membersNsub_slug_147313_idx'), models.Index(fields=['is_active'], name='membersNsub_is_acti_ac6392_idx')],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('serial_number', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('maintenance_needed', 'Maintenance Needed'), ('under_maintenance', 'Under Maintenance'), ('decommissioned', 'Decommissioned')], default='operational', max_length=25)),
                ('purchased_at', models.DateField(blank=True, null=True)),
                ('last_maintenance', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='membersNsubscription.gym')),
            ],
            options={
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='CoursePopularity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_title', models.TextField()),
                ('level', models.TextField(blank=True)),
                ('total_runs', models.IntegerField(default=0)),
                ('avg_fill_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('total_attendees', models.IntegerField(default=0)),
                ('no_show_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('peak_day_of_week', models.SmallIntegerField(blank=True, null=True)),
                ('peak_hour', models.SmallIntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='popularity_records', to='users.coachprofile')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_popularity', to='membersNsubscription.gym')),
            ],
            options={
                'db_table': 'course_popularity',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.TextField()),
                ('calories_burned', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('duration_minutes', models.SmallIntegerField(blank=True, null=True)),
                ('activity_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='membersNsubscription.gym')),
            ],
            options={
                'db_table': 'activity_logs',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_reports', to='membersNsubscription.equipment')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_reports', to='membersNsubscription.gym')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_maintenance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'maintenance_reports',
            },
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('type', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('session_pack', 'Session Pack'), ('trial', 'Trial')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('session_limit', models.IntegerField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_plans', to='membersNsubscription.gym')),
            ],
            options={
                'db_table': 'membership_plans',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='membersNsubscription.gym')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('course_reminder', 'Course Reminder'), ('subscription_renewal', 'Subscription Renewal'), ('warning_issued', 'Warning Issued'), ('promotion', 'Promotion'), ('general', 'General'), ('recommendation', 'Recommendation')], max_length=30)),
                ('title', models.TextField()),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='membersNsubscription.gym')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'members_notifications',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='membersNsubscription.gym')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='membersNsubscription.gym')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.SmallIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='membersNsubscription.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='membersNsubscription.product')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('capacity', models.SmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='membersNsubscription.gym')),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all_levels', 'All Levels')], default='all_levels', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('max_participants', models.SmallIntegerField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancellation_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='users.coachprofile')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='membersNsubscription.gym')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='membersNsubscription.room')),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('remaining_sessions', models.IntegerField(blank=True, null=True)),
                ('pause_days_used', models.IntegerField(default=0)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='membersNsubscription.gym')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='membersNsubscription.membershipplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('online', 'Online'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('reference', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='membersNsubscription.gym')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='membersNsubscription.subscription')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pause_start', models.DateTimeField()),
                ('pause_end', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='membersNsubscription.subscription')),
            ],
            options={
                'db_table': 'subscription_pauses',
            },
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('type', models.CharField(choices=[('no_show', 'No Show'), ('misconduct', 'Misconduct'), ('payment', 'Payment'), ('other', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='membersNsubscription.gym')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members_issued_warnings', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_warnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'members_warnings',
            },
        ),
        migrations.CreateModel(
            name='CourseInterestScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('view_count', models.IntegerField(default=0)),
                ('booked_count', models.IntegerField(default=0)),
                ('attended_count', models.IntegerField(default=0)),
                ('cancelled_count', models.IntegerField(default=0)),
                ('no_show_count', models.IntegerField(default=0)),
                ('interest_score', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_scores', to='membersNsubscription.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_interest_scores', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_interest_scores', to='membersNsubscription.gym')),
            ],
            options={
                'db_table': 'course_interest_scores',
                'unique_together': {('gym', 'user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='CoachPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_month', models.DateField()),
                ('total_courses', models.IntegerField(default=0)),
                ('total_reservations', models.IntegerField(default=0)),
                ('attendance_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('no_show_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('cancellation_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('avg_participants', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='users.coachprofile')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_performances', to='membersNsubscription.gym')),
            ],
            options={
                'db_table': 'coach_performances',
                'unique_together': {('gym', 'coach', 'period_month')},
            },
        ),
        migrations.CreateModel(
            name='MemberBehaviorEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('course_viewed', 'Course Viewed'), ('course_booked', 'Course Booked'), ('course_cancelled', 'Course Cancelled'), ('course_attended', 'Course Attended'), ('course_no_show', 'Course No Show'), ('coach_viewed', 'Coach Viewed'), ('equipment_used', 'Equipment Used'), ('product_viewed', 'Product Viewed'), ('product_purchased', 'Product Purchased'), ('plan_viewed', 'Plan Viewed')], max_length=30)),
                ('entity_type', models.TextField(blank=True)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_events', to='membersNsubscription.gym')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'member_behavior_events',
                'indexes': [models.Index(fields=['gym', 'user', 'event_type'], name='member_beha_gym_id_8769a2_idx'), models.Index(fields=['occurred_at'], name='member_beha_occurre_13ec56_idx')],
            },
        ),
        migrations.CreateModel(
            name='MemberPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all_levels', 'All Levels')], max_length=20, null=True)),
                ('preferred_days', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('preferred_times', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('preferred_coach_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
                ('disliked_course_types', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_preferences', to='membersNsubscription.gym')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'member_preferences',
                'unique_together': {('gym', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fitness_goal', models.TextField(blank=True, default='')),
                ('medical_notes', models.TextField(blank=True, default='')),
                ('emergency_contact', models.TextField(blank=True, default='')),
                ('warning_count', models.SmallIntegerField(default=0)),
                ('suspended_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_profiles', to='membersNsubscription.gym')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_member_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['gym', 'user'], name='membersNsub_gym_id_4b2070_idx')],
                'unique_together': {('gym', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MemberRetentionSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days_since_last_visit', models.IntegerField(default=0)),
                ('bookings_last_30_days', models.IntegerField(default=0)),
                ('bookings_prev_30_days', models.IntegerField(default=0)),
                ('attendance_rate_last_30', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('churn_risk_score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('signal', models.CharField(choices=[('healthy', 'Healthy'), ('at_risk', 'At Risk'), ('churning', 'Churning'), ('churned', 'Churned')], default='healthy', max_length=15)),
                ('last_evaluated', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_signals', to='membersNsubscription.gym')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'member_retention_signals',
                'indexes': [models.Index(fields=['signal'], name='member_rete_signal_6328bf_idx'), models.Index(fields=['churn_risk_score'], name='member_rete_churn_r_46871e_idx')],
                'unique_together': {('gym', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('cancelled', 'Cancelled'), ('attended', 'Attended'), ('no_show', 'No Show'), ('waitlisted', 'Waitlisted')], default='reserved', max_length=20)),
                ('waitlist_pos', models.SmallIntegerField(blank=True, null=True)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('attended_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='membersNsubscription.course')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='membersNsubscription.gym')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservations',
                'unique_together': {('course', 'user')},
            },
        ),
        migrations.CreateModel(
            name='UserGymRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('member', 'Member'), ('coach', 'Coach'), ('admin', 'Admin')], default='member', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_user_roles', to='membersNsubscription.gym')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_gym_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['gym', 'status'], name='membersNsub_gym_id_17b4ed_idx'), models.Index(fields=['user', 'status'], name='membersNsub_user_id_f939e0_idx')],
                'unique_together': {('gym', 'user')},
            },
        ),
    ]
