# Generated by Django 5.0.4 on 2026-03-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_enable_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='require_2fa',
            field=models.BooleanField(default=False, help_text='Force all staff (coaches and admins) to enable 2FA.'),
        ),
    ]
