# Generated by Django 5.0.4 on 2026-03-11 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_gym_require_2fa'),
        ('notifications', '0002_alter_notificationlog_status_userdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='gyms.gym'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='gyms.gym'),
        ),
    ]
