# Generated by Django 5.0.4 on 2026-03-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notificationlog_status_userdevice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notificationlog",
            old_name="attempted_at",
            new_name="timestamp",
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name="notificationlog",
            name="delivered_at",
        ),
        migrations.RemoveField(
            model_name="notificationlog",
            name="provider_id",
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="raw_payload",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="channel",
            field=models.CharField(
                choices=[
                    ("in_app", "In-App"),
                    ("email", "Email"),
                    ("push", "Push"),
                    ("sms", "SMS"),
                ],
                max_length=10,
            ),
        ),
    ]
